spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/minicampus
    driver-class-name: org.mariadb.jdbc.Driver
    username: minicampus_user
    password: a1234
  
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true
  
  mail:
    host: smtp.gmail.com
    port: 587
    username: gamil@gmail.com
    password: gamilpassword
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            
logging:
  level:
    root: info


mybatis:
  mapper-locations: mybatis/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

